USE [master]
GO

CREATE DATABASE [RBAC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RBAC', FILENAME = N'/var/opt/mssql/data/RBAC.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RBAC_log', FILENAME = N'/var/opt/mssql/data/RBAC_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RBAC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RBAC] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RBAC] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RBAC] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RBAC] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RBAC] SET ARITHABORT OFF 
GO

ALTER DATABASE [RBAC] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RBAC] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RBAC] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RBAC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RBAC] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RBAC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RBAC] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RBAC] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RBAC] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RBAC] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RBAC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RBAC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RBAC] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RBAC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RBAC] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RBAC] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RBAC] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RBAC] SET RECOVERY FULL 
GO

ALTER DATABASE [RBAC] SET  MULTI_USER 
GO

ALTER DATABASE [RBAC] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RBAC] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RBAC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RBAC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RBAC] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RBAC] SET QUERY_STORE = OFF
GO

ALTER DATABASE [RBAC] SET  READ_WRITE 
GO